name: ts
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipython=8.29.0
  - jedi=0.19.1
  - joblib=1.4.2
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libopenblas=0.3.28
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libuuid=2.38.1
  - libxgboost=2.1.2
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - mypy=1.13.0
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - numpy=2.1.3
  - openssl=3.3.2
  - pandas=2.2.3
  - pandas-stubs=2.2.3.241009
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.2
  - py-xgboost-cpu=2.1.2
  - pygments=2.18.0
  - python=3.13.0
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.13
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setuptools=75.3.0
  - six=1.16.0
  - stack_data=0.6.2
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - traitlets=5.14.3
  - types-pytz=2024.2.0.20241003
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wcwidth=0.2.13
  - xz=5.2.6
