name: autoai-ts
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - joblib=1.4.2
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libmpdec=4.0.0
  - libopenblas=0.3.28
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libuuid=2.38.1
  - libxgboost=2.1.3
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=2.2.1
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pip=24.3.1
  - py-xgboost=2.1.3
  - python=3.13.1
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.13
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.6.0
  - scipy=1.15.0
  - setuptools=75.6.0
  - six=1.17.0
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tzdata=2024b
