from typing import Protocol
import numpy.typing as npt

class Model(Protocol):
    def fit(self, X: npt.NDArray, y: npt.NDArray) -> Model: ...
    def predict(self, X: npt.NDArray) -> npt.NDArray: ...
    def score(self, X: npt.NDArray, y: npt.NDArray) -> float: ...
